FROM ubuntu:16.04
RUN apt-get update

# Install Ansible
RUN apt-get install -y software-properties-common git
# The ansible repository does not provide deb packages for Xenial yet
# https://github.com/ansible/ansible/issues/15524
# RUN apt-add-repository -y ppa:ansible/ansible
RUN apt-get update
RUN apt-get install -y ansible ufw curl

COPY initctl_faker .
RUN chmod +x initctl_faker && rm -fr /sbin/initctl && ln -s /initctl_faker /sbin/initctl

# Install Ansible inventory file
RUN echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
